# Generated by Django 4.1.3 on 2022-12-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tagam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тағам аты:')),
                ('photo', models.ImageField(upload_to='move/', verbose_name='Фото:')),
                ('definition', models.TextField(verbose_name='Анықтама:')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='Ақшасы:')),
            ],
        ),
    ]
