# Generated by Django 4.1.3 on 2022-12-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_negizgi_susyn_tatty_un_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тағам аты:')),
                ('photo', models.ImageField(upload_to='Tatty/', verbose_name='Фото:')),
                ('definition', models.TextField(verbose_name='Анықтама:')),
                ('money', models.PositiveIntegerField(default=0, verbose_name='Ақшасы:')),
            ],
        ),
    ]
