# Generated by Django 4.1.3 on 2022-12-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_salat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salat',
            name='photo',
            field=models.ImageField(upload_to='Salat/', verbose_name='Фото:'),
        ),
    ]
