# Generated by Django 4.1.3 on 2022-12-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_salat_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Aты:')),
                ('email', models.EmailField(max_length=254, verbose_name='Поштасы:')),
                ('text', models.TextField(verbose_name='Пікір:')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
