# Generated by Django 4.1.3 on 2022-12-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tapsyrys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Aты:')),
                ('number', models.CharField(max_length=50, verbose_name='Нөмері:')),
                ('adres', models.CharField(max_length=300, verbose_name='Адрес:')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
